//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coneccion
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Curso> Cursos { get; set; }
        public virtual DbSet<Leccione> Lecciones { get; set; }
        public virtual DbSet<RelCursoLeccion> RelCursoLeccions { get; set; }
        public virtual DbSet<ConfigRespuesta> ConfigRespuestas { get; set; }
        public virtual DbSet<pregunta> preguntas { get; set; }
        public virtual DbSet<Rel_usuario_cursos> Rel_usuario_cursos { get; set; }
        public virtual DbSet<RespuestasAlumno> RespuestasAlumnos { get; set; }
    }
}
