//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coneccion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rel_usuario_cursos
    {
        public int iIdRelUsuarioCurso { get; set; }
        public Nullable<int> iIdUsuario { get; set; }
        public Nullable<int> iIdCurso { get; set; }
    }
}
